apiVersion: v1
kind: ConfigMap
metadata:
  name: ae-config
  namespace: abhi-ejaz
data:
  NODE_ENV:             "production"
  DB_SSL:               "true"
  PRODUCT_SERVICE_URL:  "http://product-service:3001"
  CART_SERVICE_URL:     "http://cart-service:3002"
  ORDER_SERVICE_URL:    "http://order-service:3003"
  USER_SERVICE_URL:     "http://user-service:3004"
